### ISSUE TITLE
Can't compile with Rust beta

### ISSUE THREAD

**Issue by jamm** [gfx-rs/gfx_examples#17]
![screenshot 2015-04-18 03 53 11](https://cloud.githubusercontent.com/assets/526352/7213188/945c58c6-e57e-11e4-84a0-e540c24927e4.png)

**Comment by kvark** [comment]
Related - https://github.com/gfx-rs/gfx-rs/issues/676

**Comment by fkaa** [comment]
Fixed by https://github.com/gfx-rs/gfx-rs/pull/725

**Comment by kvark** [comment]
@fkaa thanks for the triage!
