### ISSUE TITLE
All crash in OS X

### ISSUE THREAD

**Issue by tioover** [gfx-rs/gfx_examples#18]
cargo run --bin triangle                        
     Running `target/debug/triangle`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Vertex(ShaderCompilationFailed)', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:768
An unknown error occurred

cargo run --bin deferred                            
   Compiling gfx-examples v0.0.5 (file:///Users/tioover/Project/gfx_examples)
src/deferred/main.rs:130:1: 130:16 warning: unused import, #[warn(unused_imports)] on by default
src/deferred/main.rs:130 #[shader_param]
                         ^~~~~~~~~~~~~~~
src/deferred/main.rs:130:1: 130:16 note: in expansion of #[shader_param]
src/deferred/main.rs:130:1: 130:16 note: expansion site
     Running `target/debug/deferred`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Fragment(ShaderCompilationFailed)', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:768
An unknown error occurred

cargo run --bin terrain
   Compiling gfx-examples v0.0.5 (file:///Users/tioover/Project/gfx_examples)
     Running `target/debug/terrain`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Vertex(ShaderCompilationFailed)', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:768
An unknown error occurred

OS X 10.10.3
rustc 1.0.0-nightly (6790b0e51 2015-04-11) (built 2015-04-11)

**Comment by kvark** [comment]
Some examples use GLSL-1.20 shaders for better compatibility, which OSX unfortunately doesn't support. Will be solved by providing both GLSL-1.20 and GLSL-1.50 versions.

**Comment by kvark** [comment]
The cube example should work for you.

**Comment by tioover** [comment]
src/cube/main.rs:108:34: 108:66 error: this function takes 2 parameters but 3 parameters were supplied [E0061]
    src/cube/main.rs:108     let texture = canvas.factory.create_texture_rgba8(1, 1, true).unwrap();

**Comment by tioover** [comment]
terrain success running with:

    static VERTEX_SRC: &'static [u8] = b"
        #version 330 core

        layout(location = 0) in vec3 a_Pos;
        layout(location = 1) in vec3 a_Color;
        out vec3 v_Color;

        uniform mat4 u_Model;
        uniform mat4 u_View;
        uniform mat4 u_Proj;

        void main() {
            v_Color = a_Color;
            gl_Position = u_Proj * u_View * u_Model * vec4(a_Pos, 1.0);
        }
    ";

    static FRAGMENT_SRC: &'static [u8] = b"
        #version 330 core

        in vec3 v_Color;
        out vec4 color;

        void main() {
            color = vec4(v_Color, 1.0);
        }
    ";
Just....

![screenshot](http://ww3.sinaimg.cn/bmiddle/62c1e01egw1eredgdqykfj212w0tkmz9.jpg)

**Comment by tioover** [comment]
And `cube` all right now.

**Comment by csherratt** [comment]
I think we will have to apply a similar patch https://github.com/PistonDevelopers/glutin_window/pull/29 to https://github.com/gfx-rs/gfx_window_glutin. I don't have a retina display to test with (unfortunately).

**Comment by tioover** [comment]
I can try to do it

**Comment by kvark** [comment]
Fixed by #5
